name: Batch Builder Template

on:
  workflow_call:
    inputs:
      batch_number:
        description: The batch number for the build batch script
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

env:
  REGISTRY: ghcr.io
  GHCR_URI: ghcr.io/${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          github_access_token: ${{ secrets.GH_TOKEN }}

      - name: Nix build
        run: |
          chmod +x ./scripts/build_batch_${{ inputs.batch_number }}.sh
          ./scripts/build_batch_${{ inputs.batch_number }}.sh

      - name: Load images
        run: |
          chmod +x ./load_all.sh
          ./load_all.sh

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Push images
        run: |
          set -e

          images=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep '^rce/' || true)

          IFS=$'\n'
          for image in ${images}; do
            tag_name="${GHCR_URI}/$(basename "${image}")"

            echo "Tagging ${image} as ${tag_name}..."
            docker tag "${image}" "${tag_name}"

            echo "Pushing ${tag_name}..."
            docker push "${tag_name}"

            echo "Setting ${tag_name} visibility to public..."
            gh api --method PATCH -H "Accept: application/vnd.github.v3+json" "/user/packages/container/${tag_name}/visibility" -f visibility=public

            echo "Connecting ${tag_name} package to repository..."
            gh api --method PUT -H "Accept: application/vnd.github.v3+json" "/user/packages/container/${tag_name}/repository" -f repository="${{github.repository}}"
          done
          unset IFS
